[target.thumbv7em-none-eabihf]
#runner = [ "arm-none-eabi-gdb", "-q", "-ex", "target remote :3333", "-ex", "mon reset halt", "-ex", "load" ]
runner = "probe-run --chip STM32F303VCTx"
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"
